### ISSUE TITLE
Secure backend

### ISSUE THREAD

**Issue by gavinquach** [gavinquach/no-name-further-web-asm#5]
NodeJS and Express servers.
- [x] Application Security
  * [x]  Use flat Promise chains : Changed Call back function -> Async function
  * [x] Perform input validation : Check Input validation from  Vi 's original code
        -  Several requests need more specific requirements for input validation 
        - Validation in router ? Do we need to validate for schema object ? => Need Vi discussion
  * [x] Set request size limits:   Check request size limits from  Vi's original code
           1.  optimize request with crud image to cloud storage ( Vi work uploaded images to the server ? Need any changes to 
           improve performance ? ) 
           2.  pagination get API to limit object per request
           [ ] limit object 
  * [x]  Monitor the event loop
  * [x] Take precautions against brute-forcing
  * [x] Remove unnecessary routes
        - Need to ask Vi to restructure/ refactor  Controller - Router to easier handle
- [x] Error & Exception Handling
  * [x] Handle errors in asynchronous calls
- [x] Platform Security
  * [x]  Keep your packages up-to-date

**Comment by koumi15cancer** [comment]
- [x] Application Security
  * [x]  Use flat Promise chains : Changed Call back function -> Async function
  * [ ] Perform input validation : Check Input validation from  Vi 's original code
  * [ ] Set request size limits:   Check request size limits from  Vi 's original code
        + [ ] optimize request with crud image to cloud storage
  * [ ] Perform application activity logging
  * [ ]  Monitor the event loop
  * [ ] Take precautions against brute-forcing
  * [ ] Use Anti-CSRF tokens
- [x] Error & Exception Handling
  * [ ] Handle uncaughtException
  * [ x] Handle errors in asynchronous calls
  * [ ] Listen to errors when using EventEmitter
  * [ ] Handle errors in asynchronous calls
- [ ] Server Security
  * [ ] Set cookie flags appropriately
  * [ ] Use appropriate security headers
  * [ ] X-Download-Options:
- [ ]Platform Security
  * [x]  Keep your packages up-to-date
